### ISSUE TITLE
ability to take picture when someone try to unlock the device.

### ISSUE THREAD

**Issue by yuvalabou** [Decad3nce/Aegis#30]

**Comment by Decad3nce** [comment]
So take a picture on multiple failed attempts, or every time the phone gets unlocked?

I can do either, or both.

**Comment by yuvalabou** [comment]
I think 3 attampts will be that, so if theres a thive, we will also get picture of him to mail, it can use gmail account on the device:)

**Comment by TheNewSound** [comment]
is anyone still working on this app or?
