### ISSUE TITLE
warning when set "no password on login"

### ISSUE THREAD

**Issue by yuvalabou** [Decad3nce/Aegis#33]

**Comment by Decad3nce** [comment]
I could do that, just a dialog?

# 

EDIT:
Also what should the warning contain?

**Comment by yuvalabou** [comment]
sorry..
dialog that tells the user about the risk of letting anyone to enter the app, changing settings and tracking the device.

sorry for the bad english, i'm just learning.

**Comment by Decad3nce** [comment]
Won't fix. Just going to make the intro more clear.
