### ISSUE TITLE
Dependencies are undefined

### ISSUE THREAD

**Issue by farzaam** [Decad3nce/Aegis#55]
Thanks for the great work, but i can't build this app from source codes because i couldn't find relevant libraries(or maybe needed source codes). also the version of library is important to avoid mistakes. so please make a clear pom or at least write about them in some file.

**Comment by Decad3nce** [comment]
I'll update with relevant libraries as submodules as soon as I have time.

**Comment by farzaam** [comment]
Thanks :)

**Comment by farzaam** [comment]
Still waiting :) because i have a little opportunity to learn from your codes; but i promise that i will contribute to your project by adding a new language and also make a clear pom file for you.

**Comment by Decad3nce** [comment]
Closing this as submodules were added.
