### ISSUE TITLE
Update permission explanation in Play Store description

### ISSUE THREAD

**Issue by pgschk** [Decad3nce/Aegis#66]
Hi,

I just noticed, that you never updated the Play Store description after changing the manifest in Commit 63d0fc1f4cb998dd954f47111dd632cb8e7093f7.

Since reading contacts and SMS are rather sensitive permissions, it might help if you updated the description to explain why these permissions are needed and how they are used. People tend to be picky about these permissions (including me), and it's likely, that the discrepancy between what you request and what you explain keeps some people from using the app, even though it is open source

I don't really see where and why you need access to contacts and SMS (even though there really is only a minor difference between read SMS and receive SMS ;-))

Thanks!

**Comment by Decad3nce** [comment]
Ah, yep. I was slacking on updating the play store description.

The reasons for the ability to get accounts, read sms, read call log, write call log, and to read contacts is all part of the implementation of the backup accounts.

As I'm updating on the play store:

Get Accounts:
This allows the application to retrieve the names of the gmail accounts on the device for backup services.

Read SMS:
This allows the application to backup the SMS' on your device to a backup service of your choice.

Read Contacts:
This allows the application to match numbers in your sms/call logs to real contacts on your device while doing a backup.

Read Call Log:
This allows the application to recover call logs to backup service of your choice.

Write Call Log:
Also needed while matching.

**Comment by pgschk** [comment]
Great, thank you. Totally forgot about the backup feature. Thanks for updating the Play store description!

Let me know if you want a DE translation of the description (maybe put it as a .txt in git, so everybody could translate if the wanted to).
