### ISSUE TITLE
Dismiss alarm notification when pressed

### ISSUE THREAD

**Issue by c00ller** [Decad3nce/Aegis#78]
After the alarm is activated, a notification appears saying the sound settings has been changed. Tapping on it opens aeGis but does not dismiss the notification itself, which seems like non-standard behavior for this type of notification. Was this intended?

**Comment by Decad3nce** [comment]
The new method of alarm does it exactly like that. Stops alarm when notification is clicked. See https://github.com/Decad3nce/Aegis/commit/5839ea59b85dd1d253311ed60f2222bacec38281#L1R88
